#!/usr/bin/env bash
# This script installs Nginx, configures a custom 404 page, and restarts the server.

# Install Nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# Create a custom 404 page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>Ceci n'est pas une page</h1>
</body>
</html>" | sudo tee /var/www/html/404.html > /dev/null

# Create a snippet file for custom error pages
echo "error_page 404 /404.html;
location = /404.html {
    internal;
}" | sudo tee /etc/nginx/snippets/error_pages.conf > /dev/null

# Include the custom error pages snippet in the default server block
sudo sed -i '/^\tserver_name _;/ r /etc/nginx/snippets/error_pages.conf' /etc/nginx/sites-available/default

# Test Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx
sudo systemctl restart nginx

exit 0

